#!/usr/bin/python2.7
# Launcher script for the botomfa module

import argparse
import botomfa

parser = argparse.ArgumentParser()
parser.add_argument('--duration',
                    help='Duration in seconds for the temporary'
                    ' credentials to remain valid.', default=900)

args = parser.parse_args()
botomfa.run(args.duration)
